branches:
  only: 
    - master

os: linux
dist: focal

language: rust

jobs:
  include:
    - name: amd64-linux-msrv
      arch: amd64
      rust: 1.46.0 # MSRV

    - name: amd64-linux-stable
      arch: amd64
      rust: stable

    - name: amd64-linux-nightly
      arch: amd64
      rust: nightly

    - name: arm64-linux-msrv
      arch: arm64
      rust: 1.46.0 # MSRV

    - name: arm64-linux-stable
      arch: arm64
      rust: stable

    - name: arm64-linux-nightly
      arch: arm64
      rust: nightly

  allow_failures:
    - rust: nightly
    - arch: arm64 # FIXME: test failed on ARM64
  fast_finish: true

cache: cargo

script:
  - rustup component add rustfmt # ectd-rs depends on rustfmt
  - sudo apt update && sudo apt install cmake g++ libprotobuf-dev protobuf-compiler
  - cargo build --verbose
  - ./scripts/travis-ci.sh
