branches:
  only: 
    - master

arch:
  - amd64
  - arm64

os: 
  - linux

language: rust

rust:
  - stable
  - nightly
  - 1.46.0 # MSRV

jobs:
  allow_failures:
    - rust: nightly
    - arch: arm64 # FIXME: test failed on ARM64
  fast_finish: true

cache: cargo

script:
  - cargo build --verbose
  - ./scripts/test.sh
