version: '3.9'

networks:
  my_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: kvcache-etcd
    networks:
      my_subnet:
        ipv4_address: 192.168.1.10
    command: |
      /usr/local/bin/etcd
      --name etcd0
      --data-dir /etcd-data
      --advertise-client-urls http://192.168.1.10:2379
      --listen-client-urls http://0.0.0.0:2379
    # ports:
      # - "2379:2379"

  kvcache-master:
    image: docker.io/library/kvcache:kvcache
    container_name: kvcache-master
    networks:
      my_subnet:
        ipv4_address: 192.168.1.11
    environment:
      - LOG_LEVEL=debug
      - IP=192.168.1.11
      - PORT=2789
      - ETCD_ENDPOINT=http://192.168.1.10:2379
    command: >
      /usr/local/bin/kvcache
      -l debug
      -i 192.168.1.11
      -p 2789
      -e http://192.168.1.10:2379
    depends_on:
      - etcd

  kvcache-slave-1:
    image: docker.io/library/kvcache:kvcache
    container_name: kvcache-slave-1
    networks:
      my_subnet:
        ipv4_address: 192.168.1.12
    environment:
      - LOG_LEVEL=debug
      - IP=192.168.1.12
      - PORT=2789
      - ETCD_ENDPOINT=http://192.168.1.10:2379
    command: >
      /usr/local/bin/kvcache
      -l debug
      -i 192.168.1.12
      -p 2789
      -e http://192.168.1.10:2379
    depends_on:
      - etcd

  kvcache-slave-2:
    image: docker.io/library/kvcache:kvcache
    container_name: kvcache-slave-2
    networks:
      my_subnet:
        ipv4_address: 192.168.1.13
    environment:
      - LOG_LEVEL=debug
      - IP=192.168.1.13
      - PORT=2789
      - ETCD_ENDPOINT=http://192.168.1.10:2379
    command: >
      /usr/local/bin/kvcache
      -l debug
      -i 192.168.1.13
      -p 2789
      -e http://192.168.1.10:2379
    depends_on:
      - etcd