ARG RUST_IMAGE_VERSION=latest
FROM rust:${RUST_IMAGE_VERSION} as builder
ARG APT_MIRROR=mirrors.bfsu.edu.cn
ARG CARGO_INDEX=https://mirrors.bfsu.edu.cn/git/crates.io-index.git
ENV APT_MIRROR ${APT_MIRROR}
ENV CARGO_INDEX ${CARGO_INDEX}
WORKDIR /tmp/build
COPY . .
RUN sed -i "s/[a-z]*.debian.org/${APT_MIRROR}/g" /etc/apt/sources.list && \
    mkdir -p .cargo && \
    echo "[source.crates-io]\nreplace-with = 'mirror'\n[source.mirror]\nregistry =\"${CARGO_INDEX}\" " > .cargo/config
RUN apt-get update && apt-get install -y cmake g++ libprotobuf-dev protobuf-compiler
RUN cargo build --release

FROM ubuntu as datenlord
LABEL maintainers="DatenLord Authors"
LABEL description="DatenLord Distributed Storage"

COPY --from=builder /tmp/build/target/release/datenlord /usr/local/bin/datenlord
COPY --from=builder /tmp/build/scripts/setup/umount-in-container.sh /usr/local/bin/umount-in-container.sh
COPY --from=builder /tmp/build/scripts/build/datenlord-entrypoint.sh /usr/local/bin/datenlord-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/datenlord-entrypoint.sh"]
CMD []
