# https://github.com/actions-rs/audit-check#scheduled-audit

name: Security audit
on:
  schedule:
    - cron: '0 0 * * *' # at midnight of each day

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
